m4_changequote([[[,]]])m4_dnl
m4_changecom(,)m4_dnl
m4_define([[[CONFIG_DECLS_M4]]],[[[config-decls.m4]]])m4_dnl
m4_define([[[CONFIG_BASH_COMMAND]]],[[[/bin/bash]]])m4_dnl
m4_define([[[CONFIG_PROCESS_DOC_COMMAND]]],[[[/Users/wr/working/tools/bin/process-doc]]])m4_dnl
m4_define([[[CONFIG_CHECK_DOC_COMMAND]]],[[[/Users/wr/working/tools/bin/check-doc]]])m4_dnl
m4_define([[[CONFIG_CHECK_SCHEMATRON_COMMAND]]],[[[/Users/wr/working/tools/bin/check-schematron]]])m4_dnl
m4_define([[[CONFIG_SCHEMATRON_COMMAND]]],[[[/Users/wr/working/tools/bin/schematron]]])m4_dnl
m4_define([[[CONFIG_XSDVALID_COMMAND]]],[[[/Users/wr/working/tools/bin/xsdvalid]]])m4_dnl
m4_define([[[CONFIG_SAXON_COMMAND]]],[[[/Users/wr/working/tools/bin/saxon]]])m4_dnl
m4_define([[[CONFIG_CONSOLIDATE_SCHEMAS_COMMAND]]],[[[/Users/wr/working/tools/bin/consolidate-schemas]]])m4_dnl
m4_define([[[CONFIG_SVN_WDIFF_HTML_COMMAND]]],[[[/Users/wr/working/tools/bin/svn-wdiff-html]]])m4_dnl
m4_define([[[CONFIG_MKDIR_COMMAND]]],[[[/opt/local/bin/gmkdir]]])m4_dnl
m4_define([[[CONFIG_RSYNC_COMMAND]]],[[[/usr/bin/rsync]]])m4_dnl
m4_define([[[CONFIG_ZIP_COMMAND]]],[[[/usr/bin/zip]]])m4_dnl
m4_define([[[CONFIG_RM_COMMAND]]],[[[/opt/local/bin/grm]]])m4_dnl
m4_define([[[CONFIG_DOC_PROCESSING_COMMON_XSL]]],[[[/Users/wr/working/tools/share/doc-processing/common.xsl]]])m4_dnl
m4_define([[[CONFIG_DOC_PROCESSING_DOC_TO_XHTML_XSL]]],[[[/Users/wr/working/tools/share/doc-processing/doc-to-xhtml.xsl]]])m4_dnl
m4_define([[[CONFIG_COMMON_DECLS_M4]]],[[[/Users/wr/r/niem/ndr/doc/common-decls.m4]]])m4_dnl
m4_define([[[CONFIG_NDR_FUNCTIONS_XSL]]],[[[/Users/wr/working/tools/tmp/ndr-functions.xsl]]])m4_dnl
m4_define([[[CONFIG_PRODUCTS]]],[[[Makefile dependent.mk reconfigure config-decls.m4 postinstall]]])m4_dnl
