#!/usr/bin/env bash

. "$HOME"/share/wrtools-core/opt_help.bash
. "$HOME"/share/wrtools-core/fail.bash

#HELP:COMMAND_NAME: Run some convenient stuff
#HELP:Usage: COMMAND_NAME $global-options* $command ...
#HELP:global-options:
#HELP:  --help | -h: Print this help

OPTIND=1
while getopts :h-: option
do
    case "$option" in
        h ) opt_help;;
        - )
            case "$OPTARG" in
                help ) opt_help;;
                help=* ) fail "Long option \"${OPTARG%%=*}\" has an unexpected argument";;
                * ) fail "Unknown long option \"${OPTARG%%=*}\"";;
            esac
            ;;  
        '?' ) fail "unknown option \"$OPTARG\"";;
        : ) fail "option \"$OPTARG\" missing argument";;
        * ) assert false;;
    esac
done
shift $((OPTIND - 1))

#HELP:Commands:

(( $# >= 1 )) || fail "Need at least one command"
command=$1
shift

case $command in
    #HELP:  log: get the log from the last dev-ndr-4.0beta2 to dev
    log )
        (
            (( $# == 0 )) || fail "unexepected args $*"
            cd "$(dirname "$0")"
            exec 3>&1
            git log --reverse --pretty=format:%B dev-ndr-4.0beta2..dev | tee /dev/fd/3 | pbcopy
        ) ;;

    #HELP:  catlog: concatenate a bunch of log entries
    #HELP:    usage: COMMAND_NAME catlog $old-commit..$new-commit
    catlog )
        (
            cd "$(dirname "$0")"
            exec 3>&1
            git log --reverse --pretty=format:%B "$@" | tee /dev/fd/3 | pbcopy
        ) ;;

    #HELP:  rebuild: rebuild everything from nothing
    rebuild )
        (
            (( $# == 0 )) || fail "unexepected args $*"
            cd "$(dirname "$0")"
            make distclean
            make depend depend=build
            time make -j 8 valid all
        )
        ;;
    #HELP:  build $targets... : rebuild carefully
    #HELP:    default targets: valid all
    build )
        (
            cd "$(dirname "$0")"
            if (( $# == 0 ))
            then set valid all
            fi
            make depend depend=build
            time make -j 8 "$@"
        )
        ;;
    
    * )
        fail "Unknown command \"$1\"";;
esac
         

