#!/bin/bash

. ~/working/tools/lib/script-helper.bash

while getopts :h-: option
do
    case "$option" in
        h ) opt_help;;
        - )
            case "$OPTARG" in
                help ) opt_help;;
                * ) fail "unknown long option \"$OPTARG\"";;
            esac
            ;;
        '?' ) fail "unknown option \"$OPTARG\"";;
        ':' ) fail "option missing argument \"$OPTARG\"";;
        * ) assert false;;
    esac
done

INPUT=$(mktemp)
INPUT_UNIX=$(mktemp)
INPUT_HEAD=$(mktemp)
EXPECTED=$(mktemp)
cat <<EOF > "$EXPECTED"
<?xml version="1.0" encoding="US-ASCII"?>
EOF

cleanup () {
    rm -f "$INPUT" "$INPUT_UNIX" "$EXPECTED"
}
trap cleanup 0

while test $# -gt 0
do
    ensure "argument is not a file: $1" test -f "$1"
    ensure "argument is not readable: $1" test -r "$1"

    echo '# cat'

    cat "$1" > "$INPUT"

    echo '# tr'

    tr -d '\r' < "$INPUT" > "$INPUT_UNIX"

    echo '# diff input unix'

    diff "$INPUT" "$INPUT_UNIX"

    echo '# head'

    head -n 1 < "$INPUT_UNIX" > "$INPUT_HEAD"
    
    echo '# diff'

    diff -u "$EXPECTED" "$INPUT_HEAD"

    echo '# OK'

    shift
done

